### ISSUE TITLE
Modernizr is not defined

### ISSUE THREAD

**Issue by guguxh** [ChasmSolacer/Haxball-Client-Expansion#2]
![image](https://user-images.githubusercontent.com/61206153/234423843-eea6925b-6a9e-4aaa-9aaf-41d94fd21b85.png)

**Comment by ChasmSolacer** [comment]
Exactly this happens after an update, which causes source codes mismatch. Usually a simple folder name change (eg. from xxx to yyy) is enough to let it load.
As of writing this reply, this is fixed, but unfortunately it is going to be an arms race for a while

**Comment by ChasmSolacer** [comment]
Exactly this happens after an update, which causes source codes mismatch. Usually a simple folder name change (eg. from 7OirlY7R to 39gY913G) is enough to let it load.
As of writing this reply, this is fixed, but unfortunately it is going to be an arms race for a while

**Comment by ChasmSolacer** [comment]
Exactly this happens after an update that changes the folder name. Usually a simple replacement of eg. 7OirlY7R with 39gY913G in _play_ file and folder renaming is enough to get it to load (with the older game version)
As of writing this comment, this is fixed, however the arms race will remain for a while

**Comment by ChasmSolacer** [comment]
Added a workaround to prevent this kind of thing happening
